-- MySQL Script generated by MySQL Workbench
-- Thu Apr  9 00:39:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbML
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbML
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbML` DEFAULT CHARACTER SET utf8 ;
USE `dbML` ;

-- -----------------------------------------------------
-- Table `dbML`.`VENDEDORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbML`.`VENDEDORES` (
  `idVENDEDORES` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `TELEFONO` DOUBLE NULL,
  `LOCALIDAD` VARCHAR(45) NULL,
  PRIMARY KEY (`idVENDEDORES`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbML`.`ITEMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbML`.`ITEMS` (
  `id` INT NOT NULL,
  `tittle` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `seller_id` INT NULL,
  `category_id` VARCHAR(45) NULL,
  `start_time` DATETIME NULL,
  `stop_time` DATETIME NULL,
  `last_update` DATETIME NULL,
  `date_created` DATETIME NULL,
  `geo_lat` POINT NULL,
  `geo_lon` POINT NULL,
  PRIMARY KEY (`id`),
  INDEX `seller_id_idx` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `vendedor`
    FOREIGN KEY (`seller_id`)
    REFERENCES `dbML`.`VENDEDORES` (`idVENDEDORES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbML`.`PRECIOS_HIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbML`.`PRECIOS_HIST` (
  `ITEMS_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `precio_item` FLOAT NULL,
  PRIMARY KEY (`date`),
  INDEX `fk_PRECIOS_ITEMS_idx` (`ITEMS_id` ASC) VISIBLE,
  CONSTRAINT `fk_PRECIOS_ITEMS`
    FOREIGN KEY (`ITEMS_id`)
    REFERENCES `dbML`.`ITEMS` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbML`.`ALERTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbML`.`ALERTAS` (
  `id` INT NOT NULL,
  `tittle` VARCHAR(45) NULL,
  `categoria` VARCHAR(45) NULL,
  `query` VARCHAR(45) NULL,
  `precio_min` INT NULL,
  `precio_max` INT NULL,
  `item_estado` VARCHAR(45) NULL,
  `ITEMS_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ITEMS_id`),
  INDEX `fk_ALERTAS_ITEMS1_idx` (`ITEMS_id` ASC) VISIBLE,
  CONSTRAINT `fk_ALERTAS_ITEMS1`
    FOREIGN KEY (`ITEMS_id`)
    REFERENCES `dbML`.`ITEMS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
